name: mobile_assessment
description: Irecharge mobile team assessment

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts:
  json_annotation: ^4.8.1

  # State Management
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^13.0.0

  # Database
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3

  # HTTP
  dio: ^5.4.0

  # UI & Responsiveness
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable:
  build_runner:

#flutter_icons:
#  ios: true
#  android: true
#  image_path_ios: 'assets/images/logo_transparent.png'
#  image_path_android: 'assets/images/logo_transparent.png'

flutter:

  uses-material-design: true

  # assets:
  #   - assets/responses/
